global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#sergey_slabnov'
